# fly.toml file generated for dotpad on 2022-01-24T18:48:02-03:00

app = "dotpad"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  YPERSISTENCE="/data"

[mounts]
  source="dotpad_persistence"
  destination="/data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 1234
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
